config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"

  resources :users, only: [:edit, :update, :index, :show] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :following, :followers
      post :search
    end
  end

  resources :books, only: [:create,:edit, :update, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]

  resources :groups, only: [:new, :create, :edit, :update, :index, :show] do
    resources :event_messages, only: [:new, :create, :index]
    resource :group_users, only: [:create, :destroy]
  end

 get '/search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body,
    presence: true,
    length: { maximum: 200 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event_message.rb
class EventMessage < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :group
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users, dependent: :destroy
    has_many :event_messages, dependent: :destroy
    attachment :image

    validates:name,
      presence: true,
      length: { in: 2..20 }
    validates:introduction,
      length: { maximum: 50 }

    def group_users?(user)
      group_users.where(user_id: user).exists?
    end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :group_users, dependent: :destroy

  attachment :profile_image

  validates:name,
    uniqueness: true,
    length: { in: 2..20 }
  validates:introduction,
    length: { maximum: 50 }

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    following.include?(user)
  end

  def ratio(after,before)
    if before == 0
      "前日(前週)の投稿が0のため計算できません"
    else
    (after / before.to_f * 100).round.to_s + "%"
    end
  end

  def week_date(num)
    books.where(created_at: Date.today.ago(num.days).all_day).count
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_user, only: [:edit,:update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @group_user = GroupUser.create(group_id: @group.id, user_id: current_user.id)
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @group_users = @group.group_users
  end

  def index
    @groups = Group.all
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image, :owner_id).merge(owner_id: current_user.id)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    if current_user != @group.owner_id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">

      <%= render "post_comments/error", obj:@group %>

      <h1>Editing Group</h1>
      <%= form_with model: @group, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, "グループ名" %><br>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "紹介文" %><br>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image, "グループ画像"%>
          <%= f.attachment_field :image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Group", class:"btn btn-success"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-md-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "shared/side", user:current_user, book:Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <table class="table">
        <tr>
         <th></th>
         <th>グループ名</th>
         <th>紹介文</th>
         <th>メンバー数</th>
         <th></th>
        </tr>
        <% @groups.each do |group| %>
          <tr>
            <td><%= attachment_image_tag group, :image, :fill, 50, 50, fallback: "no-image-icon.jpg" %></td>
            <td>
              <%= link_to group_path(group) do %>
                <%= group.name %>
              <% end %>
            </td>
            <td><%= group.introduction %></td>
            <td><%= group.group_users.count %></td>
            <% if current_user.id == group.owner_id %>
              <td><%= link_to "Edit", edit_group_path(group.id), class:"btn btn-success" %></td>
            <% else %>
              <% if group.group_users?(current_user) %>
                <td><%= link_to "Leave this group", group_group_users_path(group), method: :delete, class:"btn btn-danger" %></td>
              <% else %>
                <td><%= link_to "Join this group", group_group_users_path(group), method: :post, class:"btn btn-success" %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>Create Group</h1>

      <%= render "post_comments/error", obj:@group %>

      <%= form_with model: @group, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, "グループ名" %><br>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "紹介文" %><br>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image, "グループ画像"%>
          <%= f.attachment_field :image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Group", class:"btn btn-success"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-md-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "shared/side", user:current_user, book:Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table">
        <tr>
         <th></th>
         <th>グループ名</th>
         <th>紹介文</th>
         <th>メンバー</th>
         <th></th>
        </tr>
        <tr>
          <td><%= attachment_image_tag @group, :image, :fill, 50, 50, fallback: "no-image-icon.jpg" %></td>
          <td>
            <%= @group.name %>
          </td>
          <td><%= @group.introduction %></td>
          <td>
            <% @group_users.each do |group_user| %>
              <%= group_user.user.name %><br>
            <% end %>
          </td>
          <% if current_user.id == @group.owner_id %>
            <td><%= link_to "Edit", edit_group_path(@group.id), class:"btn btn-success" %></td>
            <td><%= link_to "Notice an Event", new_group_event_message_path(@group), class:"btn btn-primary" %></td>
          <% else %>
            <% if @group.group_users?(current_user) %>
              <td><%= link_to "Leave this group", group_group_users_path(@group), method: :delete, class:"btn btn-danger" %></td>
              <td><%= link_to "information", group_event_messages_path(@group), class:"btn btn-primary" %></td>
            <% else %>
              <td><%= link_to "Join this group", group_group_users_path(@group), method: :post, class:"btn btn-success" %></td>
            <% end %>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>