config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"

  resources :users, only: [:edit, :update, :index, :show] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :following, :followers
      post :search
    end
  end

  resources :books, only: [:create,:edit, :update, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]

  resources :groups, only: [:new, :create, :edit, :update, :index, :show] do
    resources :event_messages, only: [:new, :create, :index]
    resource :group_users, only: [:create, :destroy]
  end

 get '/search' => 'searches#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :group_users, dependent: :destroy

  attachment :profile_image

  validates:name,
    uniqueness: true,
    length: { in: 2..20 }
  validates:introduction,
    length: { maximum: 50 }

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    following.include?(user)
  end

  def ratio(after,before)
    if before == 0
      "前日(前週)の投稿が0のため計算できません"
    else
    (after / before.to_f * 100).round.to_s + "%"
    end
  end

  def week_date(num)
    books.where(created_at: Date.today.ago(num.days).all_day).count
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit,:update]

  def edit
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(params_user)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(id: "DESC")

    @today_book = @books.where(created_at: Time.zone.now.all_day).count
    @yesterday_book = @books.where(created_at: 1.day.ago.all_day).count
    @this_week = @books.where(created_at: Date.today.ago(6.days)..Time.current).count
    @last_week = @books.where(created_at: Date.today.ago(13.days)..Date.today.ago(6.days)).count

    unless @user == current_user
      other_user_rooms = @user.entries.pluck(:room_id)
      @entry = Entry.find_by(user_id: current_user, room_id: other_user_rooms)
      if @entry.present?
        @room = @entry.room
      else
        @new_room = Room.new
        @new_entry = Entry.new
      end
    end
  end

  def following
    @users  = User.find(params[:id]).following
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  def search
    @user  = User.find(params[:id])
    @books_count =@user.books.where(created_at: params[:content].in_time_zone.all_day).count
    render "books_count"
  end



  private

  def params_user
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_books_count.html.erb
<h3>検索結果</h3>
<table class="table table-bordered">
  <tr>
    <th>投稿数</th>
  </tr>
  <tr>
    <td>
      <%= books_count %>
    </td>
  </tr>
</table>

app/views/users/books_count.js.erb
$(".books_count").html("<%= j(render "books_count", books_count: @books_count) %>");
$("#inputDate").val('')

app/views/users/edit.html.erb
<div class ="container">
  <div class="row">
    <div class="mx-auto col-5 px-0">
      <h2>User info</h2>
      <% if @user.errors.any? %>
      <h3 class="text-danger"><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
      <% end %>

      <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="form-group">
        <label>Image</label>
        <%= f.attachment_field :profile_image, class:"form-control-file" %>
      </div>
      <div class="form-group">
        <label>Introduction</label>
        <%= f.text_area :introduction, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td>フォロー数: <%= user.following.count %></td>
      <td>フォロワー数: <%= user.followers.count %></td>
      <td><%= link_to "show", user_path(user) %></td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/users/following.html.erb
<h1>Follow Users</h1>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td>フォロー数: <%= user.following.count %></td>
      <td>フォロワー数: <%= user.followers.count %></td>
      <td><%= link_to "show", user_path(user) %></td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/users/index.html.erb
<div class="container px-md-0">
  <div class="row">

    <div class="col-md-3">
      <%= render "layouts/side", user:current_user, book:Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %>
      |
      <%= link_to "グループ一覧", groups_path %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.following.count %></td>
            <td>フォロワー数: <%= user.followers.count %></td>
            <td>
            <% unless user == current_user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォローを外す", user_relationships_path(user), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user), method: :post %>
              <% end %>
            <% end %>
            </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/side", user:@user, book:Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>

      <div class="d-flex justify-content-center">
        <h3 class>投稿数の前日比・前週比</h3>
        <div id="post_book_arrow" class="btn text-success">
          <i class="fas fa-chevron-down"></i>
        </div>
      </div>

      <script>
        $(function() {
          $('#post_book_arrow').on("click",function(){
            $('#post_book_count').slideToggle();
          });
        });
      </script>

      <div id="post_book_count">
        <table class="table table-bordered">
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
          <tr>
            <td><%= @today_book %></td>
            <td><%= @yesterday_book %></td>
            <td><%= @user.ratio(@today_book,@yesterday_book) %></td>
          </tr>
        </table>
        <table class="table table-bordered">
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
          <tr>
            <td><%= @this_week %></td>
            <td><%= @last_week %></td>
            <td><%= @user.ratio(@this_week,@last_week) %></td>
          </tr>
        </table>
        <table class="table table-bordered">
          <tr>
            <th>6日前</th><th>5日前</th><th>4日前</th><th>3日前</th><th>2日前</th><th>1日前</th><th>今日</th>
          </tr>
          <tr>
            <% 6.downto(0) do |i| %>
              <td><%= @user.week_date(i) %></td>
            <% end %>
          </tr>
        </table>
      </div>

      <h3 class="text-center mt-3">- Weekly Chart -</h3>
      <canvas id="myChart"></canvas>
      <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["6日前", "5日前", "4日前", "3日前", "2日前", "1日前", "今日"],
          datasets: [{
            label: '投稿した本の数',
            backgroundColor: "rgba(0,0,0,0)",
            borderColor: "green",
            data: [
              <%= @user.week_date(6) %>, <%= @user.week_date(5) %>, <%= @user.week_date(4) %>, <%= @user.week_date(3) %>,
              <%= @user.week_date(2) %>, <%= @user.week_date(1) %>, <%= @user.week_date(0) %>
            ]
          }]
        }
      });
      </script>
      <div>
        <%= form_with url: search_user_path(@user), local:false do |f| %>
          <%= f.date_field :content, id:"inputDate" %>
          <%= f.submit '検索', id:"button1", class:"btn btn-primary" %>
        <% end %>
      </div>

      <div class="books_count">
        <% if @books_count.present? %>
          <%= render "books_count", books_count: @books_count %>
        <% end %>
      </div>

    </div>
  </div>
</div>