config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"

  resources :users, only: [:edit, :update, :index, :show] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :following, :followers
      post :search
    end
  end

  resources :books, only: [:create,:edit, :update, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]

  resources :groups, only: [:new, :create, :edit, :update, :index, :show] do
    resources :event_messages, only: [:new, :create, :index]
    resource :group_users, only: [:create, :destroy]
  end

 get '/search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body,
    presence: true,
    length: { maximum: 200 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event_message.rb
class EventMessage < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :group
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users, dependent: :destroy
    has_many :event_messages, dependent: :destroy
    attachment :image

    validates:name,
      presence: true,
      length: { in: 2..20 }
    validates:introduction,
      length: { maximum: 50 }

    def group_users?(user)
      group_users.where(user_id: user).exists?
    end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :group_users, dependent: :destroy

  attachment :profile_image

  validates:name,
    uniqueness: true,
    length: { in: 2..20 }
  validates:introduction,
    length: { maximum: 50 }

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    following.include?(user)
  end

  def ratio(after,before)
    if before == 0
      "前日(前週)の投稿が0のため計算できません"
    else
    (after / before.to_f * 100).round.to_s + "%"
    end
  end

  def week_date(num)
    books.where(created_at: Date.today.ago(num.days).all_day).count
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def create
    @book = Book.new(params_book)
    @book.user = current_user
    if @book.save
      redirect_to book_path(@book)
      flash[:notice] = "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
  end

  def update
    if @book.update(params_book)
      redirect_to book_path(@book)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def index
    @book = Book.new
    #ソート機能
    if params[:sort] == "favorite_desc"
      @books = Book.all.sort{|a,b|
        b.favorites.where(created_at: set_week).size <=>
        a.favorites.where(created_at: set_week).size
      }
    elsif params[:category]
      @books = Book.where(category: params[:category])
    elsif params[:content]
      content = params[:content]
      @books = Book.where("title LIKE ? OR category LIKE ?", "%#{content}%","%#{content}%")
    elsif params[:sort].present?
      @books = Book.all.order(params[:sort])
    else
      @books = Book.all.order(id: 'DESC')
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    unless @book.user_id == current_user.id
      @book.book_count += 1
      @book.save
    end
    @post_comment = PostComment.new

    unless @user == current_user
      other_user_rooms = @user.entries.pluck(:room_id)
      @entry = Entry.find_by(user_id: current_user, room_id: other_user_rooms)
      if @entry.present?
        @room = @entry.room
      else
        @new_room = Room.new
      end
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def params_book
    params.require(:book).permit(:title, :body, :evaluation, :category)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def set_week
    Time.current.ago(6.days)..Time.current
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<table class="table mb-0 book-table">
<tr>
  <th class='col-2'></th>
  <th class='col-2'>Title</th>
  <th class='col-2'>Category</th>
  <th class='col-6'>Opinion</th>
</tr>
</table>
<% books.each do |book|%>
  <div class="container mb-3 py-3 rounded book-item">
    <div class="row border-bottom pb-2 align-items-center">
      <div class="col-md-2 col-4">
        <%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %>
        <% end %>
      </div>
      <div class="col-md-2 col-6 text-break">
        <%= link_to book_path(book) do %>
          <%= book.title %>
        <% end %>
      </div>
      <div class="col-md-2">
        <span class="d-inline-block d-md-none my-2 mr-1">category: </span>
        <%= link_to books_path(category: book.category) do %>
          <%= book.category %>
        <% end %>
      </div>
      <div class="col-md-6 text-break">
        <%= book.body.truncate(71, omission: '...') %>
      </div>
    </div>
    <div class="row py-2">
      <div class="col-md-2 favorite-btn<%= book.id %>">
        <%= render "favorites/favorite", book:book %>
      </div>

      <div class="col-md-3">
        コメントの数: <%= book.post_comments.count %>
      </div>
      <div class="col-md-3">閲覧数: <%= book.book_count %></div>

      <div class="col-md-4" id="star_evaluation_<%= book.id %>">
        <script>
        $('#star_evaluation_<%= book.id %>').empty();
        $('#star_evaluation_<%= book.id %>').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= book.evaluation %>
        });
        </script>
      </div>
    </div>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class ="container">
  <div class="row">
    <div class="mx-auto col-5 px-0">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <h3 class="text-danger"><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
      <% end %>

      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <label>Titel</label>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="form-group">
        <label>Opinion</label>
        <%= f.text_area :body, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :category %>
        <%= f.text_field :category, class:"form-control" %>
      </div>

      <div class="form-group" id="star-evaluation-<%= @book.id %>"></div>
      <script>
        $('#star-evaluation-<%= @book.id %>').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @book.evaluation %>,
        });
      </script>

      <div class="form-group">
        <%= f.submit "Update Book", class:"btn btn-success" %>
      </div>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div class="container px-sm-0">
  <h3 class="text-danger"><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>



<div class="container px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/side", user: current_user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <div class="sort-bar">
        <%= link_to "新しい順", books_path(sort: 'created_at DESC') %>
        |
        <%= link_to "評価が高い順", books_path(sort: "evaluation DESC") %>
        |
        <%= link_to "いいね順(1週間)", books_path(sort: :favorite_desc) %>
      </div>
      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/side", user:@book.user, book:Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <div class="row">
        <h2 class="col-7">Book detail</h2>
        <% if @book.user == current_user %>
          <div class="col-5 text-right">
            <%= link_to "Edit", edit_book_path(@book), class:"btn btn-success btn-sm mr-2" %>
            <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-danger btn-sm" %>
          </div>
        <% end %>
      </div>

      <div class="container border">
        <div class="row py-2 border-bottom">
          <div class="col-md-2">
            <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %>
            <% end %><br>
            <%= link_to user_path(@book.user) do %>
              <%= @book.user.name %>
            <% end %>
          </div>
          <div class="col-md-2">
              <%= @book.title %>
          </div>
          <div class="col-md-2">
            <%= link_to books_path(category: @book.category) do %>
              <%= @book.category %>
            <% end %>
          </div>
          <div class="col-md-6 text-break">
            <%= @book.body %>
          </div>
        </div>
        <div class="row py-2">
          <div class="col-md-2 favorite-btn<%= @book.id %>">
            <%= render "favorites/favorite", book:@book %>
          </div>

          <div class="col-md">
            コメントの数: <%= @book.post_comments.count %>
          </div>
          <div class="col-md">閲覧数: <%= @book.book_count %></div>

          <div class="col-md-4" id="star_evaluation_<%= @book.id %>">
            <script>
              $('#star_evaluation_<%= @book.id %>').empty();
              $('#star_evaluation_<%= @book.id %>').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book.evaluation %>
              });
            </script>
          </div>
        </div>
      </div>

      <div class="comments_area mt-3">
        <%= render "post_comments/comment", book:@book %>
      </div>

      <div class="error">
        <%= render "post_comments/error", obj:@post_comment %>
      </div>

      <div class="form">
        <%= render "post_comments/form", book:@book, post_comment:@post_comment %>
      </div>
    </div>
  </div>
</div>