config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"

  resources :users, only: [:edit, :update, :index, :show] do
    resource :relationships, only: [:create, :destroy]
    member do
      get :following, :followers
      post :search
    end
  end

  resources :books, only: [:create,:edit, :update, :index, :show, :destroy] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :rooms, only: [:create, :show]
  resources :messages, only: [:create]

  resources :groups, only: [:new, :create, :edit, :update, :index, :show] do
    resources :event_messages, only: [:new, :create, :index]
    resource :group_users, only: [:create, :destroy]
  end

 get '/search' => 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body,
    presence: true,
    length: { maximum: 200 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event_message.rb
class EventMessage < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :group
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users, dependent: :destroy
    has_many :event_messages, dependent: :destroy
    attachment :image

    validates:name,
      presence: true,
      length: { in: 2..20 }
    validates:introduction,
      length: { maximum: 50 }

    def group_users?(user)
      group_users.where(user_id: user).exists?
    end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  validates :message, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:name]
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_many :group_users, dependent: :destroy

  attachment :profile_image

  validates:name,
    uniqueness: true,
    length: { in: 2..20 }
  validates:introduction,
    length: { maximum: 50 }

  def follow(user_id)
    active_relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    active_relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    following.include?(user)
  end

  def ratio(after,before)
    if before == 0
      "前日(前週)の投稿が0のため計算できません"
    else
    (after / before.to_f * 100).round.to_s + "%"
    end
  end

  def week_date(num)
    books.where(created_at: Date.today.ago(num.days).all_day).count
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/abouts/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
       <h1>Welcome to <i class="fas fa-book"></i><b>Bookers</b>!</h1>
    </div>
  </div>
</div>

app/views/layouts/_notification.html.erb
<% if flash[:notice] %>
  <div class="Notification text-success">
   <% flash.each do |key, value| %>
   <%= content_tag :div, value, class: key %>
   <% end %>
  </div>
<% end %>

app/views/layouts/_side.html.erb
<h2>User info</h2>

<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to following_user_path(user) do %>
        <%= user.following.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to followers_user_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>
<div class="d-flex">
  <div>
    <% unless user == current_user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-success text-nowrap" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success text-nowrap" %>
      <% end %>
    <% end %>
  </div>
  <div>
    <% unless user.id == current_user.id %>
      <% if current_user.following?(user) && user.following?(current_user) %>
        <% if @room.present? %>
          <%= link_to "チャットを始める", room_path(@room), class: "btn btn-link text-nowrap" %>
        <% else %>
          <%= form_with model: @new_room, local:true do |f| %>
            <%= fields_for @new_entry do |e| %>
              <%= e.hidden_field :user_id, value: user.id %>
            <% end %>
            <%= f.submit "チャットを始める", class:"btn btn-link" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
    <%= link_to edit_user_path(user.id), class:"btn btn-sm btn-block btn-outline-secondary mt-4" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
</div>

<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
<div class="form-group">
  <label>Titel</label>
  <%= f.text_field :title, class:"form-control" %>
</div>
<div class="form-group">
  <label>Opinion</label>
  <%= f.text_area :body, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :category %>
  <%= f.text_field :category, class:"form-control" %>
</div>

<div class="form-group" id="star">
  <%= f.label :evaluation, "Rate" %>
  <%= f.hidden_field :evaluation, id: :review_star %>
  <script>
    $('#star').empty();
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[evaluation]',
      half: true
    });
  </script>
</div>


<div class="form-group">
  <%= f.submit "Create Book", class:"btn btn-success" %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li><%= link_to " Home", user_path(current_user), class:"fas fa-home nav-link text-light" %></li>
              <li><%= link_to " Users", users_path, class:"fas fa-users nav-link text-light" %></li>
              <li><%= link_to " Books", books_path, class:"fas fa-book-open nav-link text-light" %></li>
              <li><%= link_to " logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>
            <% else %>
              <li><%= link_to " Home", root_path, class:"fas fa-home nav-link text-light" %></li>
              <li><%= link_to " About", home_about_path, class:"fas fa-link nav-link text-light" %></li>
              <li><%= link_to " sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %></li>
              <li><%= link_to " login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %></li>
            <% end %>
            </ul>
          </div>
          <div>
            <%= form_with url: books_path, method: :get, local:true do |f| %>
              <%= f.text_field :content %>
              <%= f.submit '検索', class:"btn btn-primary"%>
            <% end %>
          </div>
        </div>
      </nav>

      <% if user_signed_in? %>
        <div class="container">
          <div class="row">
            <div class="mx-auto">
              <%= form_with url: search_path, method: :get, local:true do |f| %>
                <%= f.text_field :content %>
                <%= f.select :model, options_for_select({ User: "user", Book: "book" }) %>
                <%= f.select :method, options_for_select({ 完全一致: "perfect", 部分一致: "partial", 前方一位: "forward", 後方一致: "backward" }) %>
                <%= f.submit '検索' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </header>

    <%= render 'layouts/notification' %>

    <main class="my-3">
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_side.html.erb
<h2>User info</h2>

<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to following_user_path(user) do %>
        <%= user.following.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to followers_user_path(user) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>
<div class="d-flex">
  <div>
    <% unless user == current_user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-success text-nowrap" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success text-nowrap" %>
      <% end %>
    <% end %>
  </div>
  <div>
    <% unless user.id == current_user.id %>
      <% if current_user.following?(user) && user.following?(current_user) %>
        <% if @isRoom == true %>
          <%= link_to "チャットを始める", room_path(@roomId), class: "btn btn-link text-nowrap" %>
        <% else %>
          <%= form_with model: @room, local:true do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, value: user.id %>
            <% end %>
            <%= f.submit "チャットを始める", class:"btn btn-link" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
    <%= link_to edit_user_path(user.id), class:"btn btn-sm btn-block btn-outline-secondary mt-4" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
</div>

<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>
<div class="form-group">
  <label>Titel</label>
  <%= f.text_field :title, class:"form-control" %>
</div>
<div class="form-group">
  <label>Opinion</label>
  <%= f.text_area :body, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :category %>
  <%= f.text_field :category, class:"form-control" %>
</div>

<div class="form-group" id="star">
  <%= f.label :evaluation, "Rate" %>
  <%= f.hidden_field :evaluation, id: :review_star %>
  <script>
  　$('#star').empty();
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[evaluation]',
      half: true
    });
  </script>
</div>


<div class="form-group">
  <%= f.submit "Create Book", class:"btn btn-success" %>
</div>
<% end %>